# Generated by Django 5.1.2 on 2024-11-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_answer_isright'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='tags',
        ),
    ]
