# Generated by Django 5.1.2 on 2024-11-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_answer_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerTag',
        ),
    ]
