# Generated by Django 4.2.17 on 2024-12-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/default_profile.webp', null=True, upload_to='./uploads'),
        ),
    ]
